#!/bin/bash
mkdir -p public/images/plants

download_plant() {
    local name="$1"
    local filename="$2"
    local tag="$3"
    echo "Downloading for $name..."
    curl -L "https://loremflickr.com/800/600/plant,$tag" -o "public/images/plants/$filename"
}

download_plant "Aronia wielkoowocowa" "aronia_wielkoowocowa.jpg" "aronia"
download_plant "Azalia japońska" "azalia_japonska.jpg" "azalea"
download_plant "Azalie wielkokwiatowe" "azalie_wielkokwiatowe.jpg" "azalea"
download_plant "Barwinek większy" "barwinek_wiekszy.jpg" "vinca"
download_plant "Tulipanowiec amerykański" "tulipanowiec_amerykanski.jpg" "tuliptree"
download_plant "Forsycja pośrednia" "forsycja_posrednia.jpg" "forsythia"
download_plant "Hibiskus bagienny" "hibiskus_bagienny.jpg" "hibiscus"
download_plant "Borówka amerykańska" "borowka_amerykanska.jpg" "blueberry"
download_plant "Brzoza brodawkowata" "brzoza_brodawkowata.jpg" "birch"
download_plant "Budleja Davida" "budleja_davida.jpg" "buddleja"
download_plant "Dereń biały" "deren_bialy.jpg" "dogwood"
download_plant "Jaśminowiec wonny" "jasminowiec_wonny.jpg" "philadelphus"
download_plant "Jukka ogrodowa" "jukka_ogrodowa.jpg" "yucca"
download_plant "Kalina koralowa" "kalina_koralowa.jpg" "viburnum"
download_plant "Laurowiśnia wschodnia" "laurowisnia_wschodnia.jpg" "laurel"
download_plant "Lawenda wąskolistna" "lawenda_waskolistna.jpg" "lavender"
download_plant "Lilak pospolity" "lilak_pospolity.jpg" "lilac"
download_plant "Magnolia" "magnolia.jpg" "magnolia"
download_plant "Migdałek trójklapowy" "migdalek_trojklapowy.jpg" "almond"
download_plant "Pęcherznica kalinolistna" "pecherznica_kalinolistna.jpg" "physocarpus"
download_plant "Pięciornik krzewiasty" "pieciornik_krzewiasty.jpg" "potentilla"
download_plant "Pigwowiec pośredni" "pigwowiec_posredni.jpg" "chaenomeles"
download_plant "Platan klonolistny" "platan_klonolistny.jpg" "platanus"
download_plant "Róża pomarszczona" "roza_pomarszczona.jpg" "rose"
download_plant "Tawuła japońska" "tawula_japonska.jpg" "spiraea"
download_plant "Wiąz" "wiaz.jpg" "elm"
download_plant "Wierzba mandżurska" "wierzba_mandzurska.jpg" "willow"
download_plant "Berberys Thunberga" "berberys_thunberga.jpg" "berberis"
download_plant "Grab pospolity" "grab_pospolity.jpg" "hornbeam"
download_plant "Surmia bignoniowa" "surmia_bignoniowa.jpg" "catalpa"
download_plant "Perukowiec podolski" "perukowiec_podolski.jpg" "cotinus"
download_plant "Irga" "irga.jpg" "cotoneaster"
download_plant "Śliwa wiśniowa" "sliwa_wisniowa.jpg" "plum"
download_plant "Wiśnia" "wisnia.jpg" "cherry"
download_plant "Ognik szkarłatny" "ognik_szkarlatny.jpg" "pyracantha"
download_plant "Dąb" "dab.jpg" "oak"
download_plant "Robinia akacjowa" "robinia_akacjowa.jpg" "robinia"
download_plant "Bez czarny" "bez_czarny.jpg" "elderberry"
download_plant "Jarząb" "jarzab.jpg" "sorbus"
download_plant "Tamaryszek" "tamaryszek.jpg" "tamarix"
download_plant "Lipa drobnolistna" "lipa_drobnolistna.jpg" "linden"
download_plant "Krzewuszka" "krzewuszka.jpg" "weigela"
download_plant "Modrzewnica" "modrzewnica.jpg" "andromeda"
download_plant "Różanecznik" "rozanecznik.jpg" "rhododendron"
download_plant "Pieris japoński" "pieris_japonski.jpg" "pieris"
download_plant "Kiścień" "kicien.jpg" "leucothoe"
download_plant "Kokornak" "kokornak.jpg" "aristolochia"
download_plant "Milin amerykański" "milin_amerykanski.jpg" "campsis"
download_plant "Powojnik" "powojnik.jpg" "clematis"
download_plant "Bluszcz pospolity" "bluszcz_pospolity.jpg" "ivy"
download_plant "Wiciokrzew" "wiciokrzew.jpg" "lonicera"
download_plant "Winobluszcz" "winobluszcz.jpg" "parthenocissus"
download_plant "Glicynia chińska" "glicynia_chinska.jpg" "wisteria"
download_plant "Róże" "roze.jpg" "rose"
download_plant "Świdośliwa" "swidosliwa.jpg" "amelanchier"
